---
title: "IRFmanipulation"
output: html_document
---

```{r setup, include=FALSE}

cat("\014")  # clear console
rm(list=ls(all=TRUE))


library(magrittr)
library(tidyverse)
library(ggplot2)


knitr::opts_chunk$set(echo = TRUE)
```

```{r}
set.seed( 2 )

n = 2
colNamesX <- paste0( rep( paste0("respY", seq(n) ), n ), rep( paste0( "shockY", seq(n) ), each = n ) )
       
for( i in seq(10) ){        
mX <- rnorm( n * n ) %>% matrix( nrow = 1 ); mX

### check existence of different shocks
twoShocks <- sign( mX ) %>% rowSums %>% abs %>% `==`( ., 2 ); twoShocks

### if twoShocks TRUE, impose positive signs on the 1st and 3rd elements of the first row

if( twoShocks ){
# select the 1st and 3rd columns
mXsr <- mX[ , c( 1, 3 ) ] %>% 
  # detect their sign
  sign %>% 
  # extend the sign to all columns subject to this shock
  rep( each = 2 ) %>% 
  matrix( nrow = 1 ) %>% 
  set_colnames( colNamesX ) %>% 
  # if the 4th element is negative swap 1,2 and 3,4 columns
  # such that identification patternn is +/- and +/+.
  `*`( ., mX ) %>% 
  { if( .[, 4] < 0 ) .[ , c( 3, 4, 1, 2 ) ] else .}
}else{
  mXsr <- NULL
  
}
cat( "\n *****", mX   )  
cat( "\n *****", mXsr, "\n" )
}
```

